import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {adaptPdfiumSource} from '../build/pdfium-compat.mjs';
const require=createRequire(import.meta.url),esbuild=require(createRequire(require.resolve('wrangler/package.json')).resolve('esbuild'));
const catalogRoot=path.resolve(process.env.ELITE_CATALOG_TEST_ROOT||'../sites-catalog'),root=process.cwd();
function database(root){const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync(root+'/drizzle').filter(x=>x.endsWith('.sql')).sort())sqlite.exec(readFileSync(root+'/drizzle/'+f,'utf8'));function prepare(sql,values=[]){const stmt=sqlite.prepare(sql);return {bind(...v){return prepare(sql,v)},async first(){return stmt.get(...values)||null},async all(){return {results:stmt.all(...values)}},runSync(){const r=stmt.run(...values);return {meta:{changes:Number(r.changes)}}},async run(){return this.runSync()}}}return {sqlite,db:{prepare,async batch(statements){sqlite.exec('BEGIN');try{const results=statements.map(s=>s.runSync());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}}}}
const cdb=database(catalogRoot),odb=database(root),secret='TEST_ONLY_CATALOG_BRIDGE_SECRET_123456789';
globalThis.__catalogEnv={DB:cdb.db,ADMIN_EMAIL:'owner@elite.test',ORDER_ORIGIN:'https://order.test',CATALOG_BRIDGE_SECRET:secret};
globalThis.__orderEnv={PAYMENT_BCA_ACCOUNT_NUMBER:"1234567890",PAYMENT_BCA_ACCOUNT_HOLDER:"PEMILIK SIMULASI",PAYMENT_QRIS_KEY:"qris/test",PAYMENT_QRIS_MIME:"image/png",PAYMENT_QRIS_MERCHANT:"MERCHANT SIMULASI",DB:odb.db,CONFIG_SECRET:'TEST_ONLY_CONFIG_ENCRYPTION_SECRET_123456789',SITE_ORIGIN:'https://order.test',OWNER_EMAIL:'owner@elite.test',CATALOG_ORIGIN:'https://catalog.test',CATALOG_BRIDGE_SECRET:secret};
globalThis.__testUser={userId:'owner-test',email:'owner@elite.test'};
mkdirSync('.sites-runtime/tests',{recursive:true});
async function bundle(key,dir,contents){const result=await esbuild.build({stdin:{contents,resolveDir:dir,loader:'ts'},bundle:true,nodePaths:[path.join(root,'node_modules')],platform:'node',format:'esm',target:'node24',write:false,define:{'import.meta.env.DEV':'false'},plugins:[{name:'isolated-test',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:key,namespace:'env'}));b.onLoad({filter:/.*/,namespace:'env'},()=>({contents:`export const env=globalThis.__${key}Env;`}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'auth'}));b.onLoad({filter:/.*/,namespace:'auth'},()=>({contents:'export async function getChatGPTUser(){return globalThis.__testUser}'}));b.onLoad({filter:/index\.esm\.browser\.js$/},args=>({contents:adaptPdfiumSource(readFileSync(args.path,'utf8')),loader:'js'}));b.onResolve({filter:/pdfium\.wasm$/},()=>({path:'wasm',namespace:'wasm'}));b.onLoad({filter:/.*/,namespace:'wasm'},()=>({contents:`import {readFileSync} from 'node:fs';export default new WebAssembly.Module(readFileSync(${JSON.stringify(require.resolve('@hyzyla/pdfium/pdfium.wasm'))}));`}));}}]});const f=path.join(root,'.sites-runtime/tests/catalog-'+key+'.mjs');writeFileSync(f,result.outputFiles[0].contents);return import(pathToFileURL(f))}
const c=await bundle('catalog',catalogRoot,"export * from './lib/checkout';export {POST as publicCheckout} from './app/api/checkout/route';export {POST as internalPost} from './app/api/internal/orders/route';export {GET as publicCatalog} from './app/api/catalog/route';export {POST as adminPost} from './app/api/admin/route';");
const o=await bundle('order',root,"export * from './lib/catalog-bridge';export * from './lib/order-server';export * from './lib/fulfilment';export {POST as orderPost} from './app/api/order/route';export {POST as webhook} from './app/api/telegram/webhook/route';export {POST as proofPost} from './app/api/order/proof/route';export {GET as orderGet} from './app/api/order/route';export {POST as qrisPost} from './app/api/admin/qris/route';export {GET as proofGet} from './app/api/admin/orders/[id]/route';export {GET as invoiceGet} from './app/api/order/invoice/route';");
let deliveries=[],lostResponse=false,unavailable=false,providerCalls=0,messageId=100;
globalThis.fetch=async(input,init)=>{const u=new URL(String(input));if(u.origin==='https://catalog.test'){if(unavailable)throw new Error('simulated unavailable');const r=await c.internalPost(new Request(u,init));if(lostResponse&&JSON.parse(init.body).op==='sale'&&r.ok){lostResponse=false;throw new Error('simulated lost response after durable commit')}return r}if(u.hostname==='api.telegram.org'){const method=u.pathname.split('/').pop();const payload=init.body instanceof FormData?{chat_id:init.body.get('chat_id')}:JSON.parse(init.body);deliveries.push({method,payload});return Response.json({ok:true,result:{message_id:messageId++,url:'https://order.test/api/telegram/webhook'}})}providerCalls++;throw new Error('Real provider requests forbidden in integration tests')};
globalThis.__orderEnv.PAYMENT_QRIS_SHA256="0".repeat(64);
const quoteId='a'.repeat(64),png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
async function setup(){cdb.sqlite.exec('DELETE FROM request_limits;DELETE FROM catalog_sales;DELETE FROM catalog_checkouts;DELETE FROM stock_history;DELETE FROM size_groups;DELETE FROM products;');odb.sqlite.exec('DELETE FROM shipments;DELETE FROM telegram_receipts;DELETE FROM orders;DELETE FROM settings;DELETE FROM shipping_quotes;DELETE FROM limits;');deliveries=[];lostResponse=false;unavailable=false;providerCalls=0;globalThis.__testUser={userId:'owner-test',email:'owner@elite.test'};globalThis.__orderEnv.CATALOG_BRIDGE_SECRET=secret;
 const now=new Date().toISOString();cdb.sqlite.prepare("INSERT INTO products(id,shortcode,instagram_url,name,brand,category,price,condition,defects,status,created_at,updated_at) VALUES('p','TestPost','https://www.instagram.com/p/TestPost/','PRL Cotton Poplin Shirt — White','PRL','Kemeja',365000,'Very good','–','published',?,?)").run(now,now);
 cdb.sqlite.prepare("INSERT INTO size_groups(id,product_id,label,fits,qty) VALUES('sm','p','Fit S–M','[\"S\",\"M\"]',3),('l','p','Fit L','[\"L\"]',2)").run();
 const cipher=await o.encrypt('TEST_BOT'),hook=await o.encrypt('TEST_HOOK');odb.sqlite.prepare('INSERT INTO settings(id,owner_id,qris_key,bot_cipher,chat_id,webhook_cipher,webhook_active) VALUES(1,?,?,?,?,?,1)').run('owner-test','test-qris',cipher,'12345',hook);
 const shipping={id:quoteId,destination:{id:1,label:'Bandung',postalCode:'40375',district:'Baleendah',city:'Bandung'},amount:20000,grams:1000,service:'EZ',checkedAt:Date.now(),expiresAt:Date.now()+100000};odb.sqlite.prepare('INSERT INTO shipping_quotes(id,payload,expires_at) VALUES(?,?,?)').run(quoteId,JSON.stringify(shipping),shipping.expiresAt);
 globalThis.__orderEnv.BUCKET={async head(){return {size:png.length,httpMetadata:{contentType:"image/png"}}},async get(){return {size:png.length,arrayBuffer:async()=>png}},async put(){},async delete(){}};
}
const qty=id=>cdb.sqlite.prepare('SELECT qty FROM size_groups WHERE id=?').get(id).qty;
async function pick(lines=[{productId:'p',groupId:'l',quantity:1}]){const r=await c.publicCheckout(new Request('https://catalog.test/api/checkout',{method:'POST',headers:{origin:'https://catalog.test','content-type':'application/json'},body:JSON.stringify({lines})}));assert.equal(r.status,201,JSON.stringify(await r.clone().json()));const v=await r.json();return new URL(v.url).searchParams.get('catalog')}
async function buy(token,extra={},cookie=''){const r=await o.orderPost(new Request('https://order.test/api/order',{method:'POST',headers:{origin:'https://order.test','content-type':'application/json',...(cookie?{cookie}:{})},body:JSON.stringify({name:'Pembeli Uji',phone:'081234567890',address:'Jalan Uji Nomor 12 Bandung',postcode:'40375',consent:true,quoteId,catalogToken:token,itemAmount:1,items:['Barang palsu'],quantity:1,...extra})}));return {r,v:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}}
async function proof(order){const f=new FormData();f.set('file',new File([png],'proof.png',{type:'image/png'}));f.set('paymentMethod',order.v.payment_method);const r=await o.proofPost(new Request('https://order.test/api/order/proof',{method:'POST',headers:{origin:'https://order.test',cookie:order.cookie},body:f}));assert.equal(r.status,200);return odb.sqlite.prepare('SELECT * FROM orders WHERE id=?').get(order.v.id)}
async function callback(order,update=1,action='confirm',from=12345,hook='TEST_HOOK'){return o.webhook(new Request('https://order.test/api/telegram/webhook',{method:'POST',headers:{'content-type':'application/json','x-telegram-bot-api-secret-token':hook},body:JSON.stringify({update_id:update,callback_query:{id:'cb'+update,from:{id:from},data:action+':'+order.id,message:{message_id:Number(order.invoice_message),chat:{id:12345,type:'private'}}}})}))}
test('Pilihan S dan M memakai satu kelompok; checkout tidak menahan atau memotong stok',async()=>{await setup();const token=await pick([{productId:'p',groupId:'sm',quantity:1},{productId:'p',groupId:'sm',quantity:2}]);const q=await o.catalogQuote(token);assert.equal(q.lines.length,1);assert.equal(q.lines[0].quantity,3);assert.equal(q.amount,1095000);assert.equal(qty('sm'),3)});
test('Harga dan nama hasil manipulasi browser diganti data server; tautan tidak dapat dipakai sesi lain',async()=>{await setup();const token=await pick();const b=await buy(token);assert.equal(b.r.status,201);assert.equal(b.v.item_amount,365000);assert.equal(b.v.total,385000);assert.match(b.v.items[0],/PRL.*Fit L/);assert.equal(b.v.stock_sync_state,'pending');assert.equal((await buy(token)).r.status,409);assert.equal(qty('l'),2)});
test('Bukti dikirim tiga pesan; hanya konfirmasi pemilik memotong L 2→1',async()=>{await setup();const b=await buy(await pick());const order=await proof(b);assert.equal(deliveries.filter(x=>['sendMessage','sendDocument'].includes(x.method)).length,3);assert.equal(qty('l'),2);await callback(order,1,'confirm',999);assert.equal(qty('l'),2);assert.equal((await callback(order,2,'confirm',12345,'WRONG')).status,403);await callback(order,3);assert.equal(qty('l'),1);assert.equal(odb.sqlite.prepare('SELECT stock_sync_state FROM orders').get().stock_sync_state,'applied');assert.equal(providerCalls,0)});
test('Update Telegram duplikat, klik baru, dan klik bersamaan memotong sekali',async()=>{await setup();const order=await proof(await buy(await pick()));await Promise.all([callback(order,10),callback(order,11)]);await callback(order,10);await callback(order,12);assert.equal(qty('l'),1);assert.equal(cdb.sqlite.prepare('SELECT COUNT(*) n FROM catalog_sales').get().n,1);assert.equal(cdb.sqlite.prepare('SELECT COUNT(*) n FROM stock_history').get().n,1)});
test('Kelompok L habis hilang; S–M tetap tampil; semua habis menyembunyikan kartu',async()=>{await setup();const order=await proof(await buy(await pick([{productId:'p',groupId:'l',quantity:2}])));await callback(order);let p=(await (await c.publicCatalog()).json()).products;assert.equal(p.length,1);assert.deepEqual(p[0].groups.map(g=>g.id),['sm']);const order2=await proof(await buy(await pick([{productId:'p',groupId:'sm',quantity:3}])));await callback(order2,2);p=(await (await c.publicCatalog()).json()).products;assert.equal(p.length,0);assert.equal(qty('sm'),0)});
test('Konflik satu ukuran menolak seluruh pemotongan, pembayaran tercatat dan pengiriman ditahan',async()=>{await setup();const order=await proof(await buy(await pick([{productId:'p',groupId:'sm',quantity:1},{productId:'p',groupId:'l',quantity:2}])));cdb.sqlite.prepare("UPDATE size_groups SET qty=1 WHERE id='l'").run();await callback(order);assert.equal(qty('sm'),3);assert.equal(qty('l'),1);const row=odb.sqlite.prepare('SELECT * FROM orders').get();assert.equal(row.payment_state,'payment_confirmed');assert.equal(row.stock_sync_state,'conflict');await assert.rejects(()=>o.processShipment(order.id));assert.equal(providerCalls,0);assert.equal(cdb.sqlite.prepare('SELECT COUNT(*) n FROM catalog_sales').get().n,0);cdb.sqlite.prepare("UPDATE size_groups SET qty=2 WHERE id='l'").run();await callback(order,2,'retry');assert.equal(qty('sm'),2);assert.equal(qty('l'),0)});
test('Respons hilang sesudah commit dapat dicoba ulang tanpa potong stok ganda',async()=>{await setup();const order=await proof(await buy(await pick()));lostResponse=true;await callback(order);assert.equal(qty('l'),1);assert.equal(odb.sqlite.prepare('SELECT stock_sync_state FROM orders').get().stock_sync_state,'error');await callback(order,2,'retry');assert.equal(qty('l'),1);assert.equal(odb.sqlite.prepare('SELECT stock_sync_state FROM orders').get().stock_sync_state,'applied')});
test('Katalog tidak dapat dihubungi: simpan kesalahan dan retry setelah pulih',async()=>{await setup();const order=await proof(await buy(await pick()));unavailable=true;await callback(order);assert.equal(qty('l'),2);assert.equal(odb.sqlite.prepare('SELECT stock_sync_state FROM orders').get().stock_sync_state,'error');unavailable=false;await callback(order,2,'retry');assert.equal(qty('l'),1)});
test('Endpoint pemotongan backend menolak tanpa secret dan tidak memberi harga draf',async()=>{await setup();const r=await c.internalPost(new Request('https://catalog.test/api/internal/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op:'sale',orderId:'EV-261008-12345678',checkoutId:'x'})}));assert.equal(r.status,403);const token=await pick();cdb.sqlite.prepare("UPDATE products SET status='draft'").run();await assert.rejects(()=>o.catalogQuote(token));assert.equal(qty('l'),2)});
test('Harga berubah atau tautan kedaluwarsa ditolak sebelum pembayaran',async()=>{await setup();let token=await pick();cdb.sqlite.prepare('UPDATE products SET price=400000').run();await assert.rejects(()=>o.catalogQuote(token));await setup();token=await pick();cdb.sqlite.prepare('UPDATE catalog_checkouts SET expires_at=0').run();await assert.rejects(()=>o.catalogQuote(token));assert.equal((await buy(token)).r.status,410)});
test('Pesanan manual tetap berfungsi dan tidak menebak barang katalog dari nama',async()=>{await setup();const b=await buy(undefined,{items:['PRL Cotton Poplin Shirt · Fit L'],itemAmount:365000});assert.equal(b.r.status,201);const order=await proof(b);await callback(order);assert.equal(qty('l'),2);assert.equal(odb.sqlite.prepare('SELECT stock_sync_state FROM orders').get().stock_sync_state,'unlinked')});
test('Dua pembeli barang terakhir: hanya satu terpotong, yang lain konflik tanpa stok negatif',async()=>{await setup();cdb.sqlite.prepare("UPDATE size_groups SET qty=1 WHERE id='l'").run();const a=await proof(await buy(await pick())),b=await proof(await buy(await pick()));await Promise.all([callback(a,1),callback(b,2)]);assert.equal(qty('l'),0);assert.deepEqual(odb.sqlite.prepare('SELECT stock_sync_state FROM orders ORDER BY stock_sync_state').all().map(x=>x.stock_sync_state),['applied','conflict'])});
test('Undo stok terakhir tetap tercatat; konfirmasi lama tidak memotong ulang',async()=>{await setup();const order=await proof(await buy(await pick()));await callback(order);const h=cdb.sqlite.prepare('SELECT id FROM stock_history ORDER BY rowid DESC LIMIT 1').get();const r=await c.adminPost(new Request('https://catalog.test/api/admin',{method:'POST',headers:{origin:'https://catalog.test','content-type':'application/json'},body:JSON.stringify({op:'undo',id:'p',historyId:h.id})}));assert.equal(r.status,200);assert.equal(qty('l'),2);await callback(order,2);assert.equal(qty('l'),2)});

test('Permintaan admin anonim/akun lain tidak mengubah stok atau QRIS',async()=>{
 await setup();for(const user of [null,{userId:'intruder',email:'intruder@elite.test'}]){globalThis.__testUser=user;
 const stock=await c.adminPost(new Request('https://catalog.test/api/admin',{method:'POST',headers:{origin:'https://catalog.test','content-type':'application/json'},body:JSON.stringify({op:'stock',groupId:'l',revision:0,mode:'set',qty:100})}));assert.ok([401,403].includes(stock.status));assert.equal(qty('l'),2);
 const qris=await o.qrisPost(new Request('https://order.test/api/admin/qris',{method:'POST',headers:{origin:'https://order.test'},body:'invalid'}));assert.ok([401,403].includes(qris.status));assert.equal(odb.sqlite.prepare('SELECT qris_key FROM settings').get().qris_key,'test-qris');}
});
test('Admin tanpa Origin atau lintas situs ditolak; order lintas situs ditolak',async()=>{
 await setup();for(const origin of [undefined,'https://evil.test']){const headers={'content-type':'application/json',...(origin?{origin}:{})};assert.equal((await c.adminPost(new Request('https://catalog.test/api/admin',{method:'POST',headers,body:JSON.stringify({op:'stock',groupId:'l',revision:0,mode:'set',qty:99})}))).status,403);assert.equal((await o.orderPost(new Request('https://order.test/api/order',{method:'POST',headers,body:'{}'}))).status,403);}assert.equal(qty('l'),2);assert.equal(odb.sqlite.prepare('SELECT COUNT(*) n FROM orders').get().n,0);
});
test('Ukuran byte nyata dibatasi meski header hilang atau palsu',async()=>{
 await setup();for(const length of [undefined,'1']){const headers={'content-type':'application/json',...(length?{'content-length':length}:{})};await assert.rejects(()=>o.body(new Request('https://order.test/api/order',{method:'POST',headers,body:JSON.stringify({x:'あ'.repeat(5000)})})),e=>e.status===413);}
 const excessive=new Request('https://catalog.test/api/checkout',{method:'POST',headers:{origin:'https://catalog.test','content-type':'application/json'},body:JSON.stringify({x:'あ'.repeat(50001)})});assert.equal((await c.publicCheckout(excessive)).status,413);
 await assert.rejects(()=>o.body(new Request('https://order.test/api/order',{method:'POST',headers:{'content-type':'text/plain'},body:'{}'})),e=>e.status===415);
 const f=new FormData();f.set('file',new File([new Uint8Array(4*1024*1024+10001)],'huge.jpg',{type:'image/jpeg'}));const multipart=new Response(f),bytes=await multipart.arrayBuffer();await assert.rejects(()=>o.image(new Request('https://order.test/api/order/proof',{method:'POST',headers:{'content-type':multipart.headers.get('content-type')},body:bytes})),e=>e.status===413);
});
test('Checkout spam ditahan tanpa membuat lebih dari 60 checkout per IP/jam',async()=>{
 await setup();for(let i=0;i<60;i++)await pick();const r=await c.publicCheckout(new Request('https://catalog.test/api/checkout',{method:'POST',headers:{origin:'https://catalog.test','content-type':'application/json'},body:JSON.stringify({lines:[{productId:'p',groupId:'l',quantity:1}]})}));assert.equal(r.status,429);assert.equal(cdb.sqlite.prepare('SELECT COUNT(*) n FROM catalog_checkouts').get().n,60);assert.equal(qty('l'),2);
});
test('Batas order diperiksa sebelum request mahal ke katalog',async()=>{
 await setup();for(let i=0;i<12;i++)assert.equal((await buy('bad-token')).r.status,400);unavailable=true;assert.equal((await buy('f'.repeat(64))).r.status,429);assert.equal(odb.sqlite.prepare('SELECT COUNT(*) n FROM orders').get().n,0);
});
test('Manipulasi total/ongkir/status di browser tidak mengesahkan pembayaran',async()=>{
 await setup();const b=await buy(await pick(),{total:1,shipping_amount:0,payment_state:'payment_confirmed',status:'submitted',confirmed_by:'12345',stock_sync_state:'applied'});assert.equal(b.r.status,400);assert.equal(odb.sqlite.prepare('SELECT COUNT(*) n FROM orders').get().n,0);assert.equal(qty('l'),2);
});
test('Bukti gambar bukan bukti dana masuk; message invoice palsu tidak dapat mengonfirmasi',async()=>{
 await setup();const row=await proof(await buy(await pick()));assert.equal(row.payment_state,'proof_received');assert.equal(qty('l'),2);await callback({...row,invoice_message:'999999'},77);assert.equal(odb.sqlite.prepare('SELECT payment_state FROM orders').get().payment_state,'proof_received');assert.equal(qty('l'),2);assert.equal(providerCalls,0);
});
test('Invoice dan bukti tidak bisa diakses dengan ID saja atau cookie acak',async()=>{
 await setup();const b=await buy(await pick());await proof(b);for(const cookie of ['', 'elite_order='+ 'f'.repeat(64)]){const req=new Request('https://order.test/api/order?invoice='+b.v.id,{headers:{cookie}});assert.equal((await o.orderGet(req)).status,404);assert.equal((await o.invoiceGet(new Request('https://order.test/api/order/invoice',{headers:{cookie}}))).status,404);}
 globalThis.__testUser=null;assert.equal((await o.proofGet(new Request('https://order.test/api/admin/orders/'+b.v.id),{params:Promise.resolve({id:b.v.id})})).status,401);
});
test('Empat unit katalog menolak tarif 1 kg; tarif 2 kg tersimpan di invoice',async()=>{
 await setup();const token=await pick([{productId:'p',groupId:'sm',quantity:2},{productId:'p',groupId:'l',quantity:2}]);
 assert.equal((await buy(token,{quantity:1,grams:1000})).r.status,409);assert.equal(odb.sqlite.prepare('SELECT COUNT(*) n FROM orders').get().n,0);assert.equal(qty('sm'),3);assert.equal(qty('l'),2);
 const q=JSON.parse(odb.sqlite.prepare('SELECT payload FROM shipping_quotes WHERE id=?').get(quoteId).payload);q.grams=2000;q.amount=35000;odb.sqlite.prepare('UPDATE shipping_quotes SET payload=? WHERE id=?').run(JSON.stringify(q),quoteId);
 const b=await buy(token,{quantity:1,items:['Tampered'],grams:1000});assert.equal(b.r.status,201);assert.equal(b.v.quantity,4);assert.equal(b.v.quote.grams,2000);assert.equal(b.v.shipping_amount,35000);assert.equal(b.v.total,1495000);
});
test('Jumlah manual naik 3→4 menolak tarif lama, tanpa membuat order',async()=>{
 await setup();assert.equal((await buy(undefined,{items:['Kemeja A','Kemeja B','Kemeja C','Kemeja D'],quantity:4,itemAmount:600000})).r.status,409);assert.equal(odb.sqlite.prepare('SELECT COUNT(*) n FROM orders').get().n,0);
});
