import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(path.join(fs.realpathSync('node_modules/wrangler'),'package.json'));
const {Miniflare}=require('miniflare');
const root=path.resolve('.');
const server=path.join(root,'dist/server');const files=fs.readdirSync(server,{recursive:true}).filter(f=>f.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:a.localeCompare(b));
const mf=new Miniflare({name:'elite-qa',modulesRoot:server,modules:files.map(f=>({type:'ESModule',path:path.join(server,f)})),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{TEAM_ACCESS_SECRET:'TEST_ONLY_TEAM_ENCRYPTION_SECRET_123456789',ADMIN_EMAIL:'qa-admin@elite.test',ORDER_ORIGIN:'https://order.test',CATALOG_BRIDGE_SECRET:'TEST_ONLY_CATALOG_SECRET_1234567890'},assets:{workerName:'elite-qa',directory:path.join(root,'dist/client'),binding:'ASSETS',routerConfig:{invoke_user_worker_ahead_of_assets:true,has_user_worker:true}}});
let count=0;function pass(name){count++;console.log('PASS '+name)}
const adminHeaders={'oai-authenticated-user-id':'qa-admin-user','oai-authenticated-user-email':'qa-admin@elite.test'};
async function call(body,headers=adminHeaders){const r=await mf.dispatchFetch('http://elite.test/api/admin',{method:'POST',headers:{...headers,'Content-Type':'application/json',Origin:'http://elite.test'},body:JSON.stringify(body)});const data=await r.json();return {status:r.status,data}}
async function getAdmin(id){const r=await mf.dispatchFetch('http://elite.test/api/admin?id='+id,{headers:adminHeaders});assert.equal(r.status,200);return r.json()}
async function publicProducts(){const r=await mf.dispatchFetch('http://elite.test/api/catalog');assert.equal(r.status,200);return (await r.json()).products}
// Explicit manual form values, never caption-parser output.
const manualFields={name:'PRL Cotton Poplin Shirt — White',brand:'PRL',category:'Kemeja',features:[],color:'White',price:365000,condition:'Very good condition.',defects:'Tidak ada'};
const manualSizes=[{label:'',tagSize:'',fits:['S','M'],lengthCm:72,widthCm:50,qty:3,price:null,condition:null,defects:null},{label:'',tagSize:'',fits:['L'],lengthCm:78,widthCm:58,qty:2,price:null,condition:null,defects:null}];
async function createFixture(values={},headers=adminHeaders){
 const {draftId=crypto.randomUUID(),photoKey=null,photoKeys=[],groups=manualSizes,...fields}=values;
 const created=await call({op:'create',draftId,photoKey,photoKeys},headers);
 if(created.status!==200||created.data.duplicate)return created;
 const p=created.data.product;
 const saved=await call({...p,...manualFields,...fields,op:'save',status:'draft',reviewed:false,groups:groups.map((g,i)=>({...g,id:i===0?p.groups[0].id:crypto.randomUUID()}))},headers);
 if(saved.status===200)saved.data.duplicate=false;return saved;
}
const mainDraftId='12345678-1234-1234-1234-123456789aaa';
const caption='Legacy caption retained for audit only';
try{
 const d=await mf.getD1Database('DB');for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())for(const sql of fs.readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await d.prepare(sql).run();
 const anonymous=await mf.dispatchFetch('http://elite.test/api/admin');
 if(anonymous.status!==401)console.log('Diagnostic response',anonymous.status,(await anonymous.text()).slice(0,5000));
 assert.equal(anonymous.status,401);
 assert.equal((await call({op:'manualImport',url:'https://www.instagram.com/p/Unauthorized/',caption},{})).status,401);
 assert.equal((await call({op:'manualImport',url:'https://www.instagram.com/p/Unauthorized/',caption},{...adminHeaders,'oai-authenticated-user-email':'other@elite.test'})).status,403);pass('Pengunjung dan akun lain tidak bisa membaca admin atau menulis stok');
 const bound=await mf.dispatchFetch('http://elite.test/api/admin',{headers:adminHeaders});assert.equal(bound.status,200);
 const impostor=await call({op:'checkInstagram'},{...adminHeaders,'oai-authenticated-user-id':'other-user-same-email'});assert.equal(impostor.status,403);
 assert.equal((await d.prepare('SELECT user_id FROM admin_access WHERE id=1').first()).user_id,adminHeaders['oai-authenticated-user-id']);pass('Admin terikat ke satu identitas akun; ID lain tidak bisa mengambil alih meski email sama');

 const csrf=await mf.dispatchFetch('http://elite.test/api/admin',{method:'POST',headers:{...adminHeaders,'Content-Type':'application/json',Origin:'http://evil.test'},body:JSON.stringify({op:'checkInstagram'})});assert.equal(csrf.status,403);pass('Permintaan tulis dari origin lain ditolak');
 const missingOrigin=await mf.dispatchFetch('http://elite.test/api/admin',{method:'POST',headers:{...adminHeaders,'Content-Type':'application/json'},body:JSON.stringify({op:'checkInstagram'})});assert.equal(missingOrigin.status,403);pass('Admin tanpa Origin ditolak');
 const headerCheck=await mf.dispatchFetch('http://elite.test/admin',{headers:adminHeaders});assert.equal(headerCheck.headers.get('x-frame-options'),'DENY');assert.match(headerCheck.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(headerCheck.headers.get('referrer-policy'),'no-referrer');assert.equal(headerCheck.headers.get('cache-control'),'private, no-store');pass('Halaman admin memblokir iframe, kebocoran referrer, dan cache publik');

 const post='https://www.instagram.com/p/DeHNub0mMa2/';
 const failed=await call({op:'instagramImport',url:post});assert.equal(failed.status,410);assert.match(failed.data.error,/formulir manual/);assert.equal((await call({op:'manualImport',caption})).status,410);assert.equal((await call({op:'create',caption})).status,400);assert.equal((await call({op:'create',url:post})).status,400);assert.equal((await d.prepare('SELECT COUNT(*) AS n FROM products').first()).n,0);pass('Impor caption/Instagram ditolak di backend; tidak ada barang atau stok yang dibuat dari caption');
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
 const multipart=Buffer.concat([Buffer.from('--elite-qa\r\nContent-Disposition: form-data; name="photo"; filename="qa-only.png"\r\nContent-Type: image/png\r\n\r\n'),png,Buffer.from('\r\n--elite-qa--\r\n')]);
 const up=await mf.dispatchFetch('http://elite.test/api/photos',{method:'POST',headers:{...adminHeaders,Origin:'http://elite.test','Content-Type':'multipart/form-data; boundary=elite-qa'},body:multipart});const ud=await up.json();assert.equal(up.status,200,JSON.stringify(ud));const key=ud.photoKey;pass('Foto unggahan benar-benar disimpan dalam object storage');
 const created=await createFixture({photoKey:key,draftId:mainDraftId});assert.equal(created.status,200,JSON.stringify(created.data));let p=created.data.product;await d.prepare('UPDATE products SET instagram_url=?,caption=? WHERE id=?').bind(post,caption,p.id).run();p=(await getAdmin(p.id)).product;assert.equal(p.status,'draft');assert.equal(p.groups.length,2);assert.equal(p.groups.reduce((s,g)=>s+g.qty,0),5);assert.equal(p.price,365000);assert.deepEqual(p.groups[0].fits,['S','M']);assert.equal((await publicProducts()).length,0);assert.equal((await mf.dispatchFetch('http://elite.test/api/photos/'+key)).status,404);pass('Input manual membuat draf lima unit; draf dan foto draf tidak terlihat publik');
 const blocked=await call({...p,op:'save',status:'published',reviewed:false});assert.equal(blocked.status,400);pass('Publikasi ditolak sebelum konfirmasi admin');
 const published=await call({...p,op:'save',status:'published',reviewed:true,instagramUrl:'https://www.instagram.com/p/ChangeAttempt/',caption:'overwrite attempt'});assert.equal(published.status,200,JSON.stringify(published.data));p=published.data.product;let publicP=await publicProducts();assert.equal(publicP.length,1);assert.equal(publicP[0].instagramUrl,undefined);assert.equal(p.instagramUrl,post);assert.equal(p.caption,caption);assert.equal(publicP[0].caption,undefined);assert.equal(publicP[0].warnings,undefined);const photoResponse=await mf.dispatchFetch('http://elite.test/api/photos/'+key);assert.equal(photoResponse.status,200);assert.equal(photoResponse.headers.get('content-type'),'image/png');assert.equal((await photoResponse.arrayBuffer()).byteLength,70);pass('Data sumber lama tetap disimpan saat edit; URL Instagram/caption tidak dikirim ke publik');
 // Separate requests represent laptop and phone reading the same server database.
 const laptop=await getAdmin(p.id),phone=await getAdmin(p.id);assert.equal(laptop.product.version,phone.product.version);let l=laptop.product.groups[1];
 const sold=await call({op:'stock',groupId:l.id,revision:l.revision,mode:'delta',delta:-1});assert.equal(sold.status,200);assert.equal(sold.data.product.groups[1].qty,1);assert.equal((await getAdmin(p.id)).product.groups[1].qty,1);assert.equal((await publicProducts())[0].groups[1].qty,1);pass('L 2→1: perubahan terbaca oleh sesi lain dan katalog publik');
 const stale=await call({op:'stock',groupId:phone.product.groups[1].id,revision:phone.product.groups[1].revision,mode:'delta',delta:-1});assert.equal(stale.status,409);assert.equal((await getAdmin(p.id)).product.groups[1].qty,1);pass('Klik dengan versi stok lama ditolak; tidak menimpa stok terbaru');
 const staleSave=await call({...phone.product,op:'save',status:'published',reviewed:true});assert.equal(staleSave.status,409);assert.equal((await getAdmin(p.id)).product.groups[1].qty,1);pass('Editor lama tidak dapat mengembalikan jumlah stok');
 const duplicate=await call({op:'create',draftId:mainDraftId});assert.equal(duplicate.status,200);assert.equal(duplicate.data.duplicate,true);assert.equal(duplicate.data.product.id,p.id);assert.equal(duplicate.data.product.groups[1].qty,1);assert.equal((await publicProducts()).length,1);pass('Mencoba ulang draf yang sama tidak membuat kartu baru atau mengembalikan stok yang terjual');
 let latest=await getAdmin(p.id);l=latest.product.groups[1];const zeroL=await call({op:'stock',groupId:l.id,revision:l.revision,mode:'delta',delta:-1});assert.equal(zeroL.status,200);publicP=await publicProducts();assert.equal(publicP.length,1);assert.equal(publicP[0].groups.length,1);assert.deepEqual(publicP[0].groups[0].fits,['S','M']);pass('L habis hilang dari data publik; kelompok S–M tetap tersedia');
 latest=await getAdmin(p.id);l=latest.product.groups[1];const negative=await call({op:'stock',groupId:l.id,revision:l.revision,mode:'delta',delta:-1});assert.equal(negative.status,400);assert.equal((await getAdmin(p.id)).product.groups[1].qty,0);pass('Stok negatif ditolak tanpa perubahan');
 const undo=await call({op:'undo',id:p.id,historyId:latest.history[0].id});assert.equal(undo.status,200);assert.equal(undo.data.product.groups[1].qty,1);assert.ok(undo.data.history[0].undoOf);const undoAgain=await call({op:'undo',id:p.id,historyId:latest.history[0].id});assert.notEqual(undoAgain.status,200);pass('Undo terakhir memulihkan stok dan tercatat; undo ganda ditolak');
 latest=await getAdmin(p.id);const a=await call({op:'stock',groupId:latest.product.groups[0].id,revision:latest.product.groups[0].revision,mode:'set',qty:0});assert.equal(a.status,200);const b=await call({op:'stock',groupId:a.data.product.groups[1].id,revision:a.data.product.groups[1].revision,mode:'set',qty:0});assert.equal(b.status,200);assert.equal((await publicProducts()).length,0);assert.equal((await getAdmin(p.id)).product.status,'published');assert.ok((await getAdmin(p.id)).history.length>=6);pass('Seluruh stok habis: kartu disembunyikan dan data/riwayat tetap tersimpan');
 const badQty=await call({op:'stock',groupId:b.data.product.groups[0].id,revision:b.data.product.groups[0].revision,mode:'set',qty:1.5});assert.equal(badQty.status,400);await assert.rejects(()=>d.prepare('UPDATE size_groups SET qty=-1 WHERE id=?').bind(b.data.product.groups[0].id).run());pass('Pecahan dan stok negatif juga ditolak pada batas backend/database');
 const concurrent=await Promise.all([call({op:'stock',groupId:b.data.product.groups[0].id,revision:b.data.product.groups[0].revision,mode:'delta',delta:1}),call({op:'stock',groupId:b.data.product.groups[0].id,revision:b.data.product.groups[0].revision,mode:'delta',delta:1})]);assert.deepEqual(concurrent.map(x=>x.status).sort(),[200,409]);assert.equal((await getAdmin(p.id)).product.groups[0].qty,1);pass('Dua klik bersamaan dengan versi sama hanya diterapkan satu kali');
 const ambiguous=await call({op:'create'});assert.equal(ambiguous.status,200);assert.equal(ambiguous.data.product.name,'');assert.equal(ambiguous.data.product.category,'');assert.deepEqual(ambiguous.data.product.features,[]);assert.equal(ambiguous.data.product.caption,'');assert.equal(ambiguous.data.product.instagramUrl,'');assert.equal(ambiguous.data.product.condition,null);assert.equal(ambiguous.data.product.defects,null);assert.equal(ambiguous.data.product.price,null);assert.equal(ambiguous.data.product.groups[0].qty,null);assert.deepEqual(ambiguous.data.product.groups[0].fits,[]);assert.equal((await getAdmin(ambiguous.data.product.id)).history.length,0);const badPublish=await call({...ambiguous.data.product,op:'save',status:'published',reviewed:true});assert.equal(badPublish.status,400);assert.ok(badPublish.data.issues.length>=3);pass('Formulir manual dimulai kosong tanpa harga/fit/stok tebakan dan tidak bisa terbit sebelum dilengkapi');
 const single=await createFixture({name:'PRL Sweatshirt Crewneck — Navy',category:'Sweatshirt & Hoodie',features:['crewneck'],color:'Navy',price:300000,condition:'Good condition',photoKey:key,groups:[{...manualSizes[0],fits:['M'],lengthCm:70,widthCm:52,qty:1}]});assert.equal(single.status,200);assert.equal(single.data.product.groups.length,1);assert.equal(single.data.product.groups[0].qty,1);assert.deepEqual(single.data.product.groups[0].fits,['M']);pass('Formulir manual menyimpan satu barang, satu fit, satu unit dalam database');
 const r=await mf.dispatchFetch('http://elite.test/');assert.equal(r.status,200);const html=await r.text();assert.ok(html.includes('Koleksi tersedia'));assert.ok(html.includes('ELITE'));assert.ok(!html.includes('href="/admin"'));assert.ok(html.includes('Got question? ask us on dm or Whatsapp'));assert.ok(html.includes('href="https://wa.me/6285174389305"'));assert.ok(html.includes('href="https://www.instagram.com/elite.vtg/"'));pass('Halaman katalog dapat dirender tanpa login');
 const authPage=await mf.dispatchFetch('http://elite.test/admin',{redirect:'manual'});if(![302,303,307,308].includes(authPage.status))console.log('Auth page diagnostic',authPage.status,(await authPage.clone().text()).slice(0,1500));assert.ok([302,303,307,308].includes(authPage.status));assert.ok(authPage.headers.get('location')?.includes('/signin-with-chatgpt'));const adminPage=await mf.dispatchFetch('http://elite.test/admin',{headers:adminHeaders});assert.equal(adminPage.status,200);const adminHtml=await adminPage.text();assert.ok(adminHtml.includes('Kelola katalog'));assert.ok(!adminHtml.includes('Susun draf dari keterangan'));assert.ok(!adminHtml.includes('Koneksi</button>'));assert.ok(!adminHtml.includes('customer-support'));pass('Halaman admin mengarahkan pengunjung ke login dan merender untuk admin');
 const connection=await mf.dispatchFetch('http://elite.test/api/admin?view=connection',{headers:adminHeaders});assert.equal(connection.status,200);const cd=await connection.json();assert.equal(cd.config.configured,false);assert.equal(cd.attempts.length,0);assert.equal(cd.config.accessToken,undefined);pass('Status historis tetap hanya untuk pemilik, tanpa token dan tanpa percobaan impor baru');
 const current=(await getAdmin(p.id)).product,group=current.groups.find(x=>x.qty>0);
 const ck=await mf.dispatchFetch('http://elite.test/api/checkout',{method:'POST',headers:{Origin:'http://elite.test','Content-Type':'application/json'},body:JSON.stringify({lines:[{productId:p.id,groupId:group.id,quantity:1}]})});assert.equal(ck.status,201);const checkoutURL=new URL((await ck.json()).url);assert.equal(checkoutURL.origin,'https://order.test');const token=checkoutURL.searchParams.get('catalog');assert.equal(token.length,64);assert.equal((await getAdmin(p.id)).product.groups.find(x=>x.id===group.id).qty,1);pass('Worker checkout membuat tautan pembayaran permanen tanpa memotong stok');
 async function bridge(values,secret='TEST_ONLY_CATALOG_SECRET_1234567890'){const r=await mf.dispatchFetch('http://elite.test/api/internal/orders',{method:'POST',headers:{'Content-Type':'application/json','x-elite-bridge':secret},body:JSON.stringify(values)});return {status:r.status,data:await r.json()}}
 assert.equal((await bridge({op:'quote',token},'WRONG')).status,403);const cq=await bridge({op:'quote',token});assert.equal(cq.status,200);assert.equal(cq.data.lines[0].groupId,group.id);pass('Worker penghubung hanya menerima secret server dan membaca pilihan tersimpan');
 const sale={op:'sale',orderId:'EV-261008-ABCDEF12',checkoutId:cq.data.id,actor:'qa-owner'};const callbacks=await Promise.all([bridge(sale),bridge(sale)]);assert.deepEqual(callbacks.map(x=>x.status),[200,200]);assert.equal((await getAdmin(p.id)).product.groups.find(x=>x.id===group.id).qty,0);assert.equal((await publicProducts()).some(x=>x.id===p.id),false);assert.equal((await d.prepare('SELECT COUNT(*) AS n FROM catalog_sales').first()).n,1);pass('Transaksi D1 nyata: dua callback bersamaan hanya memotong satu kali dan menyembunyikan stok habis');
 assert.equal((await bridge({...sale,orderId:'EV-261008-ABCDEF13'})).status,409);assert.equal((await getAdmin(p.id)).product.groups.find(x=>x.id===group.id).qty,0);pass('Checkout terpakai tidak dapat memotong stok pada invoice lain');
 // Native storefront products and galleries use the same durable database and storage.
 const up2=await mf.dispatchFetch('http://elite.test/api/photos',{method:'POST',headers:{...adminHeaders,Origin:'http://elite.test','Content-Type':'multipart/form-data; boundary=elite-qa'},body:multipart});assert.equal(up2.status,200);const key2=(await up2.json()).photoKey;
 const nativeId='12345678-1234-1234-1234-123456789abc';const native=await createFixture({photoKey:key,photoKeys:[key,key2],draftId:nativeId});assert.equal(native.status,200,JSON.stringify(native.data));let np=native.data.product;assert.equal(np.instagramUrl,'');assert.equal(np.photoKeys.length,2);assert.equal(np.groups.reduce((n,g)=>n+g.qty,0),5);assert.equal((await mf.dispatchFetch('http://elite.test/api/products/'+np.id)).status,404);assert.equal((await mf.dispatchFetch('http://elite.test/api/photos/'+key2)).status,404);pass('Produk tanpa Instagram: draf lima unit dan galeri foto tetap terlindungi');
 const nativeRetry=await call({op:'create',photoKey:key,photoKeys:[key,key2],draftId:nativeId});assert.equal(nativeRetry.status,200);assert.equal(nativeRetry.data.duplicate,true);assert.equal(nativeRetry.data.product.id,np.id);pass('Percobaan ulang membuat draf manual tidak membuat produk ganda atau menimpa isian');
 const nativePublish=await call({...np,op:'save',status:'published',reviewed:true,description:'Cotton poplin. Detail dan minus sudah diperiksa.'});assert.equal(nativePublish.status,200,JSON.stringify(nativePublish.data));np=nativePublish.data.product;const detailResponse=await mf.dispatchFetch('http://elite.test/api/products/'+np.id);assert.equal(detailResponse.status,200);const dp=(await detailResponse.json()).product;assert.equal(dp.photoKeys.length,2);assert.equal(dp.description,'Cotton poplin. Detail dan minus sudah diperiksa.');assert.equal(dp.instagramUrl,undefined);assert.equal(dp.caption,undefined);assert.equal(dp.warnings,undefined);assert.equal(dp.shortcode,undefined);assert.equal((await mf.dispatchFetch('http://elite.test/api/photos/'+key2)).status,200);pass('Halaman produk publik membaca galeri dan deskripsi tanpa membocorkan caption admin');
 const detailPage=await mf.dispatchFetch('http://elite.test/produk/'+np.id);assert.equal(detailPage.status,200);const detailHtml=await detailPage.text();assert.ok(detailHtml.includes(np.name));assert.ok(detailHtml.includes('Kembali ke koleksi'));assert.ok(detailHtml.includes('Got question? ask us on dm or Whatsapp'));assert.ok(!detailHtml.includes('Postingan Instagram'));assert.equal((await mf.dispatchFetch('http://elite.test/produk/'+ambiguous.data.product.id)).status,404);pass('Permalink produk dapat dibuka tanpa login; halaman produk draf ditolak');
 const missingPhoto=await call({...np,op:'save',status:'published',reviewed:true,photoKeys:[...np.photoKeys,'11111111-1111-1111-1111-111111111111']});assert.equal(missingPhoto.status,400);assert.equal((await getAdmin(np.id)).product.photoKeys.length,2);pass('Foto yang tidak tersimpan ditolak tanpa mengubah galeri produk');
 const nativeCheckout=await mf.dispatchFetch('http://elite.test/api/checkout',{method:'POST',headers:{Origin:'http://elite.test','Content-Type':'application/json'},body:JSON.stringify({lines:[{productId:np.id,groupId:np.groups[0].id,quantity:3},{productId:np.id,groupId:np.groups[1].id,quantity:2}]})});assert.equal(nativeCheckout.status,201);const nativeToken=new URL((await nativeCheckout.json()).url).searchParams.get('catalog');const nativeQuote=await bridge({op:'quote',token:nativeToken});assert.equal(nativeQuote.status,200);assert.equal(nativeQuote.data.amount,1825000);const nativeSale=await bridge({op:'sale',orderId:'EV-261008-ABCDEF14',checkoutId:nativeQuote.data.id,actor:'qa-owner'});assert.equal(nativeSale.status,200);assert.equal((await publicProducts()).some(x=>x.id===np.id),false);const soldDetail=await mf.dispatchFetch('http://elite.test/api/products/'+np.id);assert.equal(soldDetail.status,200);assert.equal((await soldDetail.json()).product.groups.reduce((n,g)=>n+g.qty,0),0);pass('Produk mandiri lima unit bisa checkout dan terjual; hilang dari koleksi, permalink menampilkan stok habis');
 const hideNative=await call({...((await getAdmin(np.id)).product),op:'save',status:'draft',photoKeys:[key],photoKey:key});assert.equal(hideNative.status,200);assert.equal((await mf.dispatchFetch('http://elite.test/api/products/'+np.id)).status,404);assert.equal((await mf.dispatchFetch('http://elite.test/api/photos/'+key2)).status,404);pass('Mencabut produk dan galeri mencabut akses publik foto tambahan');
 const blank=await call({op:'create',draftId:'12345678-1234-1234-1234-123456789abd'});assert.equal(blank.status,200);assert.equal(blank.data.product.price,null);assert.equal(blank.data.product.reviewed,false);assert.equal((await call({...blank.data.product,op:'save',status:'published',reviewed:true})).status,400);pass('Draf kosong tetap belum diketahui dan tidak dapat terbit sebelum dilengkapi');
 const twelveKeys=[key,key2];for(let i=2;i<12;i++){const upload=await mf.dispatchFetch('http://elite.test/api/photos',{method:'POST',headers:{...adminHeaders,Origin:'http://elite.test','Content-Type':'multipart/form-data; boundary=elite-qa'},body:multipart});assert.equal(upload.status,200);twelveKeys.push((await upload.json()).photoKey)}
 const twelveDraft=await createFixture({photoKey:twelveKeys[0],photoKeys:twelveKeys,draftId:'12345678-1234-1234-1234-123456789abe'});assert.equal(twelveDraft.status,200,JSON.stringify(twelveDraft.data));assert.equal(twelveDraft.data.product.photoKeys.length,12);const twelvePublish=await call({...twelveDraft.data.product,op:'save',status:'published',reviewed:true});assert.equal(twelvePublish.status,200,JSON.stringify(twelvePublish.data));const twelvePublic=await mf.dispatchFetch('http://elite.test/api/products/'+twelveDraft.data.product.id);assert.equal(twelvePublic.status,200);assert.equal((await twelvePublic.json()).product.photoKeys.length,12);assert.equal((await mf.dispatchFetch('http://elite.test/api/photos/'+twelveKeys[11])).status,200);pass('Dua belas foto benar-benar tersimpan, dapat diterbitkan, dan dapat dibaca pembeli');
 const thirteenth=await mf.dispatchFetch('http://elite.test/api/photos',{method:'POST',headers:{...adminHeaders,Origin:'http://elite.test','Content-Type':'multipart/form-data; boundary=elite-qa'},body:multipart});assert.equal(thirteenth.status,200);const key13=(await thirteenth.json()).photoKey;const tooMany=await call({...twelvePublish.data.product,op:'save',status:'published',reviewed:true,photoKeys:[...twelveKeys,key13]});assert.equal(tooMany.status,400);assert.equal((await getAdmin(twelveDraft.data.product.id)).product.photoKeys.length,12);const tooManyDraft=await call({op:'create',photoKey:key,photoKeys:[...twelveKeys,key13]});assert.equal(tooManyDraft.status,400);pass('Foto ke-13 ditolak saat input dan edit, tanpa merusak dua belas foto tersimpan');

 // Manual sizing is editable without a buyer-facing generic group label.
 const sizing=await call({...single.data.product,op:'save',status:'published',reviewed:true,groups:[{...single.data.product.groups[0],label:'Kelompok 1',tagSize:'XXL',fits:['XL'],lengthCm:75.5,widthCm:60,qty:1}]});assert.equal(sizing.status,200,JSON.stringify(sizing.data));let sized=sizing.data.product;assert.equal(sized.groups.length,1);assert.deepEqual(sized.groups[0].fits,['XL']);assert.equal(sized.groups[0].lengthCm,75.5);assert.equal(sized.groups[0].widthCm,60);assert.equal(sized.groups[0].qty,1);const sizingPage=await mf.dispatchFetch('http://elite.test/produk/'+sized.id);assert.equal(sizingPage.status,200);const sizingHTML=await sizingPage.text();for(const value of ['Size fit to','Details size','Panjang','Lebar','75.5 cm','60 cm','XL','pcs'])assert.ok(sizingHTML.includes(value),value);assert.ok(!sizingHTML.includes('Kelompok 1'));assert.ok(!sizingHTML.includes('Size tag'));assert.ok(!sizingHTML.includes('Actual size'));pass('Fit pilihan admin, panjang/lebar manual dan stok satu unit tersimpan serta tampil tanpa label Kelompok 1');
 const sharedSizing=await call({...sized,op:'save',status:'published',reviewed:true,groups:[{...sized.groups[0],label:'',fits:['S','M'],lengthCm:72,widthCm:50}]});assert.equal(sharedSizing.status,200,JSON.stringify(sharedSizing.data));sized=sharedSizing.data.product;assert.equal(sized.groups.length,1);assert.deepEqual(sized.groups[0].fits,['S','M']);assert.equal(sized.groups[0].qty,1);const otherDevice=(await publicProducts()).find(x=>x.id===sized.id);assert.equal(otherDevice.groups[0].lengthCm,72);assert.equal(otherDevice.groups[0].widthCm,50);assert.equal(otherDevice.groups[0].qty,1);pass('Edit fit S/M tanpa label wajib tetap satu stok bersama dan ukuran terbaru terbaca sesi lain');

 const addedSize=await call({...sized,op:'save',status:'published',reviewed:true,groups:[...sized.groups,{...sized.groups[0],id:crypto.randomUUID(),label:'',tagSize:'',fits:['L'],lengthCm:78,widthCm:58,qty:2}]});assert.equal(addedSize.status,200,JSON.stringify(addedSize.data));const multiProduct=addedSize.data.product;assert.equal(multiProduct.groups.length,2);assert.equal(multiProduct.groups[0].qty,1);assert.equal(multiProduct.groups[1].qty,2);assert.deepEqual(multiProduct.groups[1].fits,['L']);assert.equal(multiProduct.groups[1].lengthCm,78);const multiPublic=(await publicProducts()).find(x=>x.id===sized.id);assert.equal(multiPublic.groups.reduce((sum,g)=>sum+g.qty,0),3);const multiPage=await mf.dispatchFetch('http://elite.test/produk/'+sized.id);assert.equal(multiPage.status,200);const multiHTML=await multiPage.text();for(const value of ['Details size','72 cm','50 cm','78 cm','58 cm'])assert.ok(multiHTML.includes(value),value);assert.ok(!multiHTML.includes('Size tag'));const stockChange=await call({op:'stock',groupId:multiProduct.groups[1].id,revision:multiProduct.groups[1].revision,mode:'delta',delta:-1});assert.equal(stockChange.status,200);assert.equal(stockChange.data.product.groups[0].qty,1);assert.equal(stockChange.data.product.groups[1].qty,1);pass('Menambah size L menyimpan ukuran dan jumlah tersendiri; penjualan L tidak mengubah stok S/M');

 async function taxonomyCall(body,headers=adminHeaders){const r=await mf.dispatchFetch('http://elite.test/api/admin/taxonomy',body?{method:'POST',headers:{...headers,Origin:'http://elite.test','Content-Type':'application/json'},body:JSON.stringify(body)}:{headers});return {status:r.status,data:await r.json()}}
 const taxonomyBefore=await taxonomyCall();assert.equal(taxonomyBefore.status,200);assert.equal(taxonomyBefore.data.features.length,9);assert.equal(taxonomyBefore.data.categories.length,6);assert.equal((await taxonomyCall(undefined,{})).status,401);assert.equal((await taxonomyCall({op:'add',label:'Unauthorized',groupId:'style'},{})).status,401);const taxonomyCSRF=await mf.dispatchFetch('http://elite.test/api/admin/taxonomy',{method:'POST',headers:{...adminHeaders,Origin:'http://evil.test','Content-Type':'application/json'},body:JSON.stringify({op:'add',label:'Unauthorized',groupId:'style'})});assert.equal(taxonomyCSRF.status,403);pass('Daftar bersama memuat enam kategori dan sembilan ciri; pengunjung dan permintaan lintas origin ditolak');
 const zipDuplicate=await taxonomyCall({op:'add',label:'Quarterzip',groupId:'opening'});assert.equal(zipDuplicate.status,409);assert.equal(zipDuplicate.data.existingId,'quarter-zip');const halfDuplicate=await taxonomyCall({op:'add',label:'Half Zip',groupId:'opening'});assert.equal(halfDuplicate.data.existingId,'half-zip');assert.equal((await taxonomyCall({op:'aliases',id:'quarter-zip',aliases:['Halfzip']})).status,409);assert.equal((await taxonomyCall()).data.features.length,9);pass('Quarterzip tidak membuat ciri duplikat; Halfzip tetap berbeda dan kedua zip tidak dapat berbagi alias');
 const newFeature=await taxonomyCall({op:'add',label:'Mock Neck',groupId:'style',aliases:['Mockneck','High Collar']});assert.equal(newFeature.status,201,JSON.stringify(newFeature.data));const mock=newFeature.data.features.find(f=>f.label==='Mock Neck');assert.ok(mock.id);const taxonomyOtherDevice=await mf.dispatchFetch('http://elite.test/api/admin',{headers:adminHeaders});assert.ok((await taxonomyOtherDevice.json()).taxonomy.features.some(f=>f.id===mock.id));const publicVocabulary=await mf.dispatchFetch('http://elite.test/api/catalog');assert.ok((await publicVocabulary.json()).taxonomy.features.some(f=>f.id===mock.id));pass('Ciri dan alias baru tersimpan di DB dan terbaca sesi admin lain serta katalog publik');
 const traitDraft=await createFixture({name:'PRL Cable Knit Quarterzip — White',category:'Sweater & Knitwear',features:['quarter-zip','cable-knit'],photoKey:key,draftId:'12345678-1234-1234-1234-123456789ac1'});assert.equal(traitDraft.status,200,JSON.stringify(traitDraft.data));assert.equal(traitDraft.data.product.name,'PRL Cable Knit Quarterzip — White');assert.equal(traitDraft.data.product.category,'Sweater & Knitwear');assert.deepEqual(traitDraft.data.product.features,['quarter-zip','cable-knit']);assert.equal(traitDraft.data.product.reviewed,false);const traitPublish=await call({...traitDraft.data.product,op:'save',status:'published',reviewed:true});assert.equal(traitPublish.status,200,JSON.stringify(traitPublish.data));let traitProduct=traitPublish.data.product;const savedTraits=await call({...traitProduct,op:'save',status:'published',reviewed:true,features:[...traitProduct.features,mock.id,mock.id]});assert.equal(savedTraits.status,200);traitProduct=savedTraits.data.product;assert.equal(traitProduct.features.length,3);assert.equal(traitProduct.groups.reduce((n,g)=>n+g.qty,0),5);const badTrait=await call({...traitProduct,op:'save',status:'published',reviewed:true,features:['free-text-quarterzip']});assert.equal(badTrait.status,400);assert.equal((await getAdmin(traitProduct.id)).product.features.length,3);const traitDetail=await mf.dispatchFetch('http://elite.test/produk/'+traitProduct.id);assert.equal(traitDetail.status,200);const traitHTML=await traitDetail.text();assert.ok(traitHTML.includes('Cable Knit'));assert.ok(traitHTML.includes('Quarter Zip'));assert.equal((await publicProducts()).filter(p=>p.id===traitProduct.id).length,1);pass('Draf Cable Knit Quarterzip mempertahankan nama asli; beberapa ciri tersimpan tanpa kartu atau stok ganda, istilah bebas ditolak');
 const legacyDraft=await createFixture({name:'PRL Crewneck — White',category:'',photoKey:key,draftId:'12345678-1234-1234-1234-123456789ac2'});assert.equal(legacyDraft.status,200);assert.equal(legacyDraft.data.product.category,'');assert.equal((await call({...legacyDraft.data.product,op:'save',status:'published',reviewed:true})).status,400);const legacyId=legacyDraft.data.product.id;await d.prepare("UPDATE products SET status='published',reviewed=1,legacy_category='Crewneck',published_at=? WHERE id=?").bind(new Date().toISOString(),legacyId).run();const legacyAdmin=(await getAdmin(legacyId)).product;assert.equal(legacyAdmin.categoryNeedsReview,true);assert.equal(legacyAdmin.legacyCategory,'Crewneck');assert.ok((await publicProducts()).some(p=>p.id===legacyId));const keepLegacy=await call({...legacyAdmin,op:'save',status:'published',reviewed:true,description:'Catatan lama tetap dapat disimpan.'});assert.equal(keepLegacy.status,200,JSON.stringify(keepLegacy.data));assert.equal(keepLegacy.data.product.groups.reduce((n,g)=>n+g.qty,0),5);pass('Kategori ambigu ditinjau admin; draf baru tidak bisa terbit, barang lama tetap publik dan dapat diedit tanpa kehilangan stok');

 // Real Worker + D1 tests for possession-based team access. No live tokens used.
 async function teamSettings(values,headers=adminHeaders){const r=await mf.dispatchFetch('http://elite.test/api/admin/team',values?{method:'POST',headers:{...headers,Origin:'http://elite.test','Content-Type':'application/json'},body:JSON.stringify(values)}:{headers});return {status:r.status,data:await r.json()}}
 const settingsTeam=await teamSettings();assert.equal(settingsTeam.status,200);assert.equal(settingsTeam.data.members.length,3);assert.equal(new Set(settingsTeam.data.members.map(m=>m.link)).size,3);const grants=settingsTeam.data.members;
 assert.deepEqual((await teamSettings()).data.members.map(m=>m.link),grants.map(m=>m.link));assert.equal((await teamSettings(undefined,{})).status,401);
 const storage=await d.prepare('SELECT token_hash,token_cipher FROM team_access').all();for(let i=0;i<3;i++){const secret=new URL(grants[i].link).hash.slice(1);assert.match(secret,/^[a-f0-9]{64}$/);assert.notEqual(storage.results[i].token_hash,secret);assert.ok(!storage.results[i].token_cipher.includes(secret))}pass('Pemilik mendapat tiga tautan unik permanen; rahasia tersimpan terenkripsi/hash dan tidak terlihat anonim');
 async function teamLogin(link,origin='http://elite.test'){const token=new URL(link).hash.slice(1);const r=await mf.dispatchFetch('http://elite.test/api/team/session',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({token})});return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],header:r.headers.get('set-cookie'),data:await r.json()}}
 const sessionA=await teamLogin(grants[0].link),sessionB=await teamLogin(grants[0].link),sessionC=await teamLogin(grants[1].link);assert.equal(sessionA.status,200);assert.equal(sessionB.status,200);assert.equal(sessionC.status,200);assert.match(sessionA.header,/HttpOnly/);assert.match(sessionA.header,/SameSite=Strict/);assert.notEqual(sessionA.cookie,sessionB.cookie);
 const staffHeaders={cookie:sessionA.cookie};const staffVocabulary=await mf.dispatchFetch('http://elite.test/api/admin',{headers:staffHeaders});assert.equal(staffVocabulary.status,200);assert.ok((await staffVocabulary.json()).taxonomy.features.some(f=>f.id===mock.id));
 const staffPage=await mf.dispatchFetch('http://elite.test/admin',{headers:staffHeaders});assert.equal(staffPage.status,200);const staffHtml=await staffPage.text();assert.ok(staffHtml.includes('Kelola katalog'));assert.ok(staffHtml.includes('Tim katalog'));assert.ok(!staffHtml.includes('Akses tim'));assert.ok(!staffHtml.includes('Koneksi</button>'));
 const privateTeamPhoto=await mf.dispatchFetch('http://elite.test/api/photos/'+key13,{headers:staffHeaders});assert.equal(privateTeamPhoto.status,200);pass('Tautan tim membuat sesi terpisah di HP/laptop, membuka dashboard dan foto draf tanpa akun pemilik');
 assert.equal((await teamLogin(grants[0].link,'http://evil.test')).status,403);const randomLink='http://elite.test/akses-tim#'+'a'.repeat(64);assert.equal((await teamLogin(randomLink)).status,403);const landing=await mf.dispatchFetch('http://elite.test/akses-tim');assert.equal(landing.status,200);assert.equal(landing.headers.get('referrer-policy'),'no-referrer');assert.equal(landing.headers.get('x-frame-options'),'DENY');assert.ok(!(await landing.text()).includes(grants[0].link));pass('Alamat halaman/tautan palsu tidak memberi akses; login lintas situs ditolak dan token tidak ada di HTML landing');
 const staffCreated=await createFixture({photoKey:key13,draftId:'12345678-1234-1234-1234-123456789abf'},staffHeaders);assert.equal(staffCreated.status,200,JSON.stringify(staffCreated.data));const staffProduct=staffCreated.data.product;assert.equal(staffProduct.status,'draft');
 const staffPublished=await call({...staffProduct,op:'save',status:'published',reviewed:true},staffHeaders);assert.equal(staffPublished.status,200);let staffGroup=staffPublished.data.product.groups[0];const staffStock=await call({op:'stock',groupId:staffGroup.id,revision:staffGroup.revision,mode:'delta',delta:-1},staffHeaders);assert.equal(staffStock.status,200);assert.equal(staffStock.data.product.groups[0].qty,2);assert.equal(staffStock.data.history[0].actorName,'Tim 1');
 const staffUpload=await mf.dispatchFetch('http://elite.test/api/photos',{method:'POST',headers:{...staffHeaders,Origin:'http://elite.test','Content-Type':'multipart/form-data; boundary=elite-qa'},body:multipart});assert.equal(staffUpload.status,200);pass('Tim dapat upload foto, menyusun draf, menerbitkan, dan mengubah stok; riwayat menandai akses tim');
 assert.equal((await teamSettings(undefined,staffHeaders)).status,401);assert.equal((await teamSettings({id:grants[1].id,action:'revoke'},staffHeaders)).status,401);assert.equal((await call({op:'checkInstagram'},staffHeaders)).status,401);assert.equal((await mf.dispatchFetch('http://elite.test/api/admin?view=connection',{headers:staffHeaders})).status,401);pass('Tim tidak dapat membaca tautan lain, membuat/mencabut akses, atau mengelola koneksi pemilik');
 assert.equal((await teamSettings({id:grants[0].id,action:'rename',name:'Pegawai Foto'})).status,200);assert.equal((await getAdmin(staffProduct.id)).history[0].actorName,'Pegawai Foto');
 const revoked=await teamSettings({id:grants[0].id,action:'revoke'});assert.equal(revoked.status,200);assert.equal(revoked.data.members[0].link,null);assert.equal((await teamLogin(grants[0].link)).status,403);for(const cookie of [sessionA.cookie,sessionB.cookie])assert.equal((await mf.dispatchFetch('http://elite.test/api/admin',{headers:{cookie}})).status,401);assert.equal((await mf.dispatchFetch('http://elite.test/api/photos/'+key13,{headers:staffHeaders})).status,200); // Published product photo remains public.
 assert.equal((await mf.dispatchFetch('http://elite.test/api/admin',{headers:{cookie:sessionC.cookie}})).status,200);pass('Pencabutan satu tautan mematikan semua sesinya; akses anggota lain tetap aktif');
 const rotated=await teamSettings({id:grants[1].id,action:'rotate'});assert.equal(rotated.status,200);assert.notEqual(rotated.data.members[1].link,grants[1].link);assert.equal((await teamLogin(grants[1].link)).status,403);assert.equal((await mf.dispatchFetch('http://elite.test/api/admin',{headers:{cookie:sessionC.cookie}})).status,401);const fresh=await teamLogin(rotated.data.members[1].link);assert.equal(fresh.status,200);pass('Mengganti tautan membatalkan token dan sesi lama, sementara tautan baru bisa masuk');
 const ended=await mf.dispatchFetch('http://elite.test/api/team/session',{method:'DELETE',headers:{Origin:'http://elite.test',cookie:fresh.cookie}});assert.equal(ended.status,200);assert.match(ended.headers.get('set-cookie'),/Max-Age=0/);assert.equal((await mf.dispatchFetch('http://elite.test/api/admin',{headers:{cookie:fresh.cookie}})).status,401);pass('Keluar menghapus sesi di server, bukan hanya menyembunyikan dashboard');
 const expiry=await teamLogin(grants[2].link);assert.equal(expiry.status,200);await d.prepare('UPDATE team_sessions SET expires_at=0 WHERE access_id=?').bind(grants[2].id).run();assert.equal((await mf.dispatchFetch('http://elite.test/api/admin',{headers:{cookie:expiry.cookie}})).status,401);await d.prepare('UPDATE team_access SET expires_at=0 WHERE id=?').bind(grants[2].id).run();assert.equal((await teamLogin(grants[2].link)).status,403);pass('Sesi 30 hari dan tautan 90 hari yang kedaluwarsa ditolak oleh backend');
 console.log(`${count} pengujian integrasi lulus. Data uji tidak masuk aplikasi produksi.`);
}finally{await mf.dispose()}
