import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {adaptPdfiumSource} from '../../sites-order/build/pdfium-compat.mjs';
const orderRoot=path.resolve(process.env.ELITE_ORDER_TEST_ROOT||'../sites-order');
const require=createRequire(orderRoot+'/package.json'),esbuild=require(createRequire(require.resolve('wrangler/package.json')).resolve('esbuild'));
const catalogRoot=process.cwd(),root=orderRoot;
function database(root){const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync(root+'/drizzle').filter(x=>x.endsWith('.sql')).sort())sqlite.exec(readFileSync(root+'/drizzle/'+f,'utf8'));function prepare(sql,values=[]){const stmt=sqlite.prepare(sql);return {bind(...v){return prepare(sql,v)},async first(){return stmt.get(...values)||null},async all(){return {results:stmt.all(...values)}},runSync(){const r=stmt.run(...values);return {meta:{changes:Number(r.changes)}}},async run(){return this.runSync()}}}return {sqlite,db:{prepare,async batch(statements){sqlite.exec('BEGIN');try{const results=statements.map(s=>s.runSync());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}}}}
const cdb=database(catalogRoot),odb=database(root),secret='TEST_ONLY_CATALOG_BRIDGE_SECRET_123456789';
globalThis.__catalogEnv={DB:cdb.db,ADMIN_EMAIL:'owner@elite.test',ORDER_ORIGIN:'https://order.test',CATALOG_BRIDGE_SECRET:secret,TEAM_ACCESS_SECRET:'TEST_ONLY_TEAM_SECRET_1234567890123456789'};
globalThis.__orderEnv={PAYMENT_BCA_ACCOUNT_NUMBER:"1234567890",PAYMENT_BCA_ACCOUNT_HOLDER:"PEMILIK SIMULASI",DB:odb.db,CONFIG_SECRET:'TEST_ONLY_CONFIG_ENCRYPTION_SECRET_123456789',SITE_ORIGIN:'https://order.test',OWNER_EMAIL:'owner@elite.test',CATALOG_ORIGIN:'https://catalog.test',CATALOG_BRIDGE_SECRET:secret};
globalThis.__testUser={userId:'owner-test',email:'owner@elite.test'};
mkdirSync('.sites-runtime/tests',{recursive:true});
async function bundle(key,dir,contents){const result=await esbuild.build({stdin:{contents,resolveDir:dir,loader:'ts'},bundle:true,nodePaths:[path.join(root,'node_modules')],platform:'node',format:'esm',target:'node24',write:false,define:{'import.meta.env.DEV':'false'},plugins:[{name:'isolated-test',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:key,namespace:'env'}));b.onLoad({filter:/.*/,namespace:'env'},()=>({contents:`export const env=globalThis.__${key}Env;`}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'auth'}));b.onLoad({filter:/.*/,namespace:'auth'},()=>({contents:'export async function getChatGPTUser(){return globalThis.__testUser}'}));b.onLoad({filter:/index\.esm\.browser\.js$/},args=>({contents:adaptPdfiumSource(readFileSync(args.path,'utf8')),loader:'js'}));b.onResolve({filter:/pdfium\.wasm$/},()=>({path:'wasm',namespace:'wasm'}));b.onLoad({filter:/.*/,namespace:'wasm'},()=>({contents:`import {readFileSync} from 'node:fs';export default new WebAssembly.Module(readFileSync(${JSON.stringify(require.resolve('@hyzyla/pdfium/pdfium.wasm'))}));`}));}}]});const f=path.join(root,'.sites-runtime/tests/team-payment-'+key+'.mjs');writeFileSync(f,result.outputFiles[0].contents);return import(pathToFileURL(f))}
const c=await bundle('catalog',catalogRoot,"export * from './lib/checkout';export {POST as publicCheckout} from './app/api/checkout/route';export {POST as internalPost} from './app/api/internal/orders/route';export {GET as publicCatalog} from './app/api/catalog/route';export {POST as adminPost} from './app/api/admin/route';export {GET as teamGet,POST as teamPost} from './app/api/admin/team/route';export {POST as teamLogin} from './app/api/team/session/route';");
const o=await bundle('order',root,"export * from './lib/catalog-bridge';export * from './lib/order-server';export * from './lib/fulfilment';export {POST as orderPost} from './app/api/order/route';export {POST as webhook} from './app/api/telegram/webhook/route';export {POST as proofPost} from './app/api/order/proof/route';export {GET as orderGet} from './app/api/order/route';export {POST as qrisPost} from './app/api/admin/qris/route';export {GET as proofGet} from './app/api/admin/orders/[id]/route';export {GET as invoiceGet} from './app/api/order/invoice/route';");
let deliveries=[],lostResponse=false,unavailable=false,providerCalls=0,messageId=100;
globalThis.fetch=async(input,init)=>{const u=new URL(String(input));if(u.origin==='https://catalog.test'){if(unavailable)throw new Error('simulated unavailable');const r=await c.internalPost(new Request(u,init));if(lostResponse&&JSON.parse(init.body).op==='sale'&&r.ok){lostResponse=false;throw new Error('simulated lost response after durable commit')}return r}if(u.hostname==='api.telegram.org'){const method=u.pathname.split('/').pop();const payload=init.body instanceof FormData?{chat_id:init.body.get('chat_id')}:JSON.parse(init.body);deliveries.push({method,payload});return Response.json({ok:true,result:{message_id:messageId++,url:'https://order.test/api/telegram/webhook'}})}providerCalls++;throw new Error('Real provider requests forbidden in integration tests')};
const quoteId='a'.repeat(64),png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
async function setup(){cdb.sqlite.exec('DELETE FROM team_sessions;DELETE FROM team_access;DELETE FROM request_limits;DELETE FROM catalog_sales;DELETE FROM catalog_checkouts;DELETE FROM stock_history;DELETE FROM size_groups;DELETE FROM products;');odb.sqlite.exec('DELETE FROM shipments;DELETE FROM telegram_receipts;DELETE FROM orders;DELETE FROM settings;DELETE FROM shipping_quotes;DELETE FROM limits;');deliveries=[];lostResponse=false;unavailable=false;providerCalls=0;globalThis.__testUser={userId:'owner-test',email:'owner@elite.test'};globalThis.__orderEnv.CATALOG_BRIDGE_SECRET=secret;
 const now=new Date().toISOString();cdb.sqlite.prepare("INSERT INTO products(id,shortcode,instagram_url,name,brand,category,price,condition,defects,status,created_at,updated_at) VALUES('p','TestPost','https://www.instagram.com/p/TestPost/','PRL Cotton Poplin Shirt — White','PRL','Kemeja',365000,'Very good','–','published',?,?)").run(now,now);
 cdb.sqlite.prepare("INSERT INTO size_groups(id,product_id,label,fits,qty) VALUES('sm','p','Fit S–M','[\"S\",\"M\"]',3),('l','p','Fit L','[\"L\"]',2)").run();
 const cipher=await o.encrypt('TEST_BOT'),hook=await o.encrypt('TEST_HOOK');odb.sqlite.prepare('INSERT INTO settings(id,owner_id,qris_key,bot_cipher,chat_id,webhook_cipher,webhook_active) VALUES(1,?,?,?,?,?,1)').run('owner-test','test-qris',cipher,'12345',hook);
 const shipping={id:quoteId,destination:{id:1,label:'Bandung',postalCode:'40375',district:'Baleendah',city:'Bandung'},amount:20000,grams:1000,service:'EZ',checkedAt:Date.now(),expiresAt:Date.now()+100000};odb.sqlite.prepare('INSERT INTO shipping_quotes(id,payload,expires_at) VALUES(?,?,?)').run(quoteId,JSON.stringify(shipping),shipping.expiresAt);
 globalThis.__orderEnv.BUCKET={async get(){return {arrayBuffer:async()=>png}},async put(){},async delete(){}};
}
const qty=id=>cdb.sqlite.prepare('SELECT qty FROM size_groups WHERE id=?').get(id).qty;
async function pick(lines=[{productId:'p',groupId:'l',quantity:1}]){const r=await c.publicCheckout(new Request('https://catalog.test/api/checkout',{method:'POST',headers:{origin:'https://catalog.test','content-type':'application/json'},body:JSON.stringify({lines})}));assert.equal(r.status,201,JSON.stringify(await r.clone().json()));const v=await r.json();return new URL(v.url).searchParams.get('catalog')}
async function buy(token,extra={},cookie=''){const r=await o.orderPost(new Request('https://order.test/api/order',{method:'POST',headers:{origin:'https://order.test','content-type':'application/json',...(cookie?{cookie}:{})},body:JSON.stringify({name:'Pembeli Uji',phone:'081234567890',address:'Jalan Uji Nomor 12 Bandung',postcode:'40375',consent:true,quoteId,catalogToken:token,itemAmount:1,items:['Barang palsu'],quantity:1,...extra})}));return {r,v:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}}
async function proof(order){const f=new FormData();f.set('file',new File([png],'proof.png',{type:'image/png'}));const r=await o.proofPost(new Request('https://order.test/api/order/proof',{method:'POST',headers:{origin:'https://order.test',cookie:order.cookie},body:f}));assert.equal(r.status,200);return odb.sqlite.prepare('SELECT * FROM orders WHERE id=?').get(order.v.id)}
async function callback(order,update=1,action='confirm',from=12345,hook='TEST_HOOK'){return o.webhook(new Request('https://order.test/api/telegram/webhook',{method:'POST',headers:{'content-type':'application/json','x-telegram-bot-api-secret-token':hook},body:JSON.stringify({update_id:update,callback_query:{id:'cb'+update,from:{id:from},data:action+':'+order.id,message:{message_id:Number(order.invoice_message),chat:{id:12345,type:'private'}}}})}))}
test('Tautan tim katalog tidak dapat mengganti QRIS, membuka bukti order, atau mengonfirmasi dana',async()=>{
 await setup();const grants=await (await c.teamGet(new Request('https://catalog.test/api/admin/team'))).json();assert.equal(grants.members.length,3);const token=new URL(grants.members[0].link).hash.slice(1);const login=await c.teamLogin(new Request('https://catalog.test/api/team/session',{method:'POST',headers:{origin:'https://catalog.test','content-type':'application/json'},body:JSON.stringify({token})}));assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/Secure/);const cookie=login.headers.get('set-cookie').split(';')[0];globalThis.__testUser=null;
 const teamStock=await c.adminPost(new Request('https://catalog.test/api/admin',{method:'POST',headers:{origin:'https://catalog.test','content-type':'application/json',cookie},body:JSON.stringify({op:'stock',groupId:'l',revision:0,mode:'delta',delta:-1})}));assert.equal(teamStock.status,200);assert.equal(qty('l'),1);
 const qris=await o.qrisPost(new Request('https://order.test/api/admin/qris',{method:'POST',headers:{origin:'https://order.test',cookie},body:'invalid'}));assert.equal(qris.status,401);assert.equal(odb.sqlite.prepare('SELECT qris_key FROM settings').get().qris_key,'test-qris');
 const orderProof=await o.proofGet(new Request('https://order.test/api/admin/orders/EV-261008-ABCDEF12',{headers:{cookie}}),{params:Promise.resolve({id:'EV-261008-ABCDEF12'})});assert.equal(orderProof.status,401);
 const hook=await o.webhook(new Request('https://order.test/api/telegram/webhook',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({update_id:1,callback_query:{id:'fake',from:{id:12345},data:'confirm:EV-261008-ABCDEF12',message:{message_id:1,chat:{id:12345,type:'private'}}}})}));assert.equal(hook.status,403);assert.equal(providerCalls,0);
 const ownerTeam=await c.teamPost(new Request('https://catalog.test/api/admin/team',{method:'POST',headers:{origin:'https://catalog.test','content-type':'application/json',cookie},body:JSON.stringify({id:grants.members[1].id,action:'revoke'})}));assert.equal(ownerTeam.status,401);
});
